ALTER TABLE users
ADD COLUMN IF NOT EXISTS study_time_minutes INTEGER NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS total_questions_answered INTEGER NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS total_correct_answers INTEGER NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS average_score NUMERIC(5,2) NOT NULL DEFAULT 0;